ig.GameConfig = {
	quitBtnURL: "https://pbskids.org/noah/games/",
	
	backgrounds: [
		{full: "background02.jpg", thumb: "bg-thumbnail02.jpg"},
		{full: "background03.jpg", thumb: "bg-thumbnail03.jpg"},
		{full: "background04.jpg", thumb: "bg-thumbnail04.jpg"},
		{full: "background05.jpg", thumb: "bg-thumbnail05.jpg"},
		{full: "background06.jpg", thumb: "bg-thumbnail06.jpg"},
		{full: "background07.jpg", thumb: "bg-thumbnail07.jpg"},
		{full: "background08.jpg", thumb: "bg-thumbnail08.jpg"},
		{full: "background09.jpg", thumb: "bg-thumbnail09.jpg"},
		{full: "background10.jpg", thumb: "bg-thumbnail10.jpg"},
		{full: "background11.jpg", thumb: "bg-thumbnail11.jpg"},
		{full: "background12.jpg", thumb: "bg-thumbnail12.jpg"},
		{full: "background13.jpg", thumb: "bg-thumbnail13.jpg"},
		{full: "background14.jpg", thumb: "bg-thumbnail14.jpg"},
		{full: "background15.jpg", thumb: "bg-thumbnail15.jpg"},
		{full: "background16.jpg", thumb: "bg-thumbnail16.jpg"},
		{full: "background17.jpg", thumb: "bg-thumbnail17.jpg"},
		{full: "background18.jpg", thumb: "bg-thumbnail18.jpg"},
		{full: "background19.jpg", thumb: "bg-thumbnail19.jpg"},
		{full: "background20.jpg", thumb: "bg-thumbnail20.jpg"}
	],

	props: [
		{id:"Prop01", sound: "lasilla", caption: "la silla"},
		{id:"Prop02", sound: "lamesa", caption: "la mesa"},
		{id:"Prop03", sound: "lamesa", caption: "la mesa"},
		{id:"Prop04", sound: "lamesa", caption: "la mesa"},
		{id:"Prop05", sound: "elsofa", caption: "el sofá"},
		{id:"Prop06", sound: "latelevision", caption: "la televisión"},
		{id:"Prop07", sound: "elpiano", caption: "el piano"},
		{id:"Prop08", sound: "lalampara", caption: "la lámpara"},
		{id:"Prop09", sound: "elrefrigerador", caption: "el refrigerador"},
		{id:"Prop10", sound: "elespejo", caption: "el espejo"},
		{id:"Prop11", sound: "elcolumpio", caption: "el columpio"},
		{id:"Prop12", sound: "eltobogan", caption: "el tobogán"},
		{id:"Prop13", sound: "elsubibaja", caption: "el subibaja"},
		{id:"Prop14", sound: "elpuestodefrutas", caption: "el puesto de frutas"},
		{id:"Prop15", sound: "laplataforma", caption: "la plataforma"},
		{id:"Prop16", sound: "elbaul", caption: "el baúl"},
		{id:"Prop17", sound: "lapecera", caption: "la pecera"},
		{id:"Prop18", sound: "elhidrante", caption: "el hidrante"},
		{id:"Prop19", sound: "elbuzon", caption: "el buzón"},
		{id:"Prop20", sound: "elcamion", caption: "el camión"},
		{id:"Prop21", sound: "elauto", caption: "el auto"},
		{id:"Prop22", sound: "elauto", caption: "el auto"},
		{id:"Prop23", sound: "elauto", caption: "el auto"},
		{id:"Prop24", sound: "elautobus", caption: "el autobús"},
		{id:"Prop25", sound: "elautobus", caption: "el autobús"},
		{id:"Prop26", sound: "elavion", caption: "el avión"},
		{id:"Prop27", sound: "elhelicoptero", caption: "el helicóptero"},
		{id:"Prop28", sound: "elhelicoptero", caption: "el helicóptero"},
		{id:"Prop29", sound: "elcamiondebomberos", caption: "el camión de bomberos"},
		{id:"Prop30", sound: "labicicleta", caption: "la bicicleta"},
		{id:"Prop31", sound: "labicicleta", caption: "la bicicleta"},
		{id:"Prop32", sound: "elsubmarino", caption: "el submarino"},
		{id:"Prop33", sound: "lacanoa", caption: "la canoa"},
		{id:"Prop34", sound: "elbarco", caption: "el barco"},
		{id:"Prop35", sound: "latabladesurf", caption: "la tabla de surf"},
		{id:"Prop36", sound: "lacarreta", caption: "la carreta"},
		{id:"Prop37", sound: "lacarretilla", caption: "la carretilla"},
		{id:"Prop38", sound: "elbalde", caption: "el balde"},
		{id:"Prop39", sound: "lapala", caption: "la pala"},
		{id:"Prop40", sound: "lapelotadefutbol", caption: "la pelota de fútbol"},
		{id:"Prop41", sound: "lasoga", caption: "la soga"},
		{id:"Prop42", sound: "elosodepeluche", caption: "el oso de peluche"},
		{id:"Prop43", sound: "losglobos", caption: "los globos"},
		{id:"Prop44", sound: "ungloborojo", caption: "un globo rojo"},
		{id:"Prop45", sound: "laescoba", caption: "la escoba"},
		{id:"Prop46", sound: "elparaguas", caption: "el paraguas"},
		{id:"Prop47", sound: "lapala", caption: "la pala"},
		{id:"Prop48", sound: "elmartillo", caption: "el martillo"},
		{id:"Prop49", sound: "lasierra", caption: "la sierra"},
		{id:"Prop50", sound: "laescalera", caption: "la escalera"},
		{id:"Prop51", sound: "elladrillo", caption: "el ladrillo"},
		{id:"Prop52", sound: "elcano", caption: "el caño"},
		{id:"Prop53", sound: "lassemillas", caption: "las semillas"},
		{id:"Prop54", sound: "lapala", caption: "la pala"},
		{id:"Prop55", sound: "laregadera", caption: "la regadera"},
		{id:"Prop56", sound: "lacanadepescar", caption: "la caña de pescar"},
		{id:"Prop57", sound: "losbinoculares", caption: "los binoculares"},
		{id:"Prop58", sound: "elplato", caption: "el plato"},
		{id:"Prop59", sound: "lacuchara", caption: "la cuchara"},
		{id:"Prop60", sound: "eltenedor", caption: "el tenedor"},
		{id:"Prop61", sound: "elcuchillo", caption: "el cuchillo"},
		{id:"Prop62", sound: "elvaso", caption: "el vaso"},
		{id:"Prop63", sound: "elbistec", caption: "el bistec"},
		{id:"Prop64", sound: "elespagueti", caption: "el espagueti"},
		{id:"Prop65", sound: "loshuevos", caption: "los huevos"},
		{id:"Prop66", sound: "lamantequilla", caption: "la mantequilla"},
		{id:"Prop67", sound: "laleche", caption: "la leche"},
		{id:"Prop68", sound: "elqueso", caption: "el queso"},
		{id:"Prop69", sound: "laszanahorias", caption: "las zanahorias"},
		{id:"Prop70", sound: "elapio", caption: "el apio"},
		{id:"Prop71", sound: "losguineos", caption: "los guineos"},
		{id:"Prop72", sound: "elguineo", caption: "el guineo"},
		{id:"Prop73", sound: "lamanzana", caption: "la manzana"},
		{id:"Prop74", sound: "lamanzana", caption: "la manzana"},
		{id:"Prop75", sound: "elhelado", caption: "el helado"},
		{id:"Prop76", sound: "elarbol", caption: "el árbol"},
		{id:"Prop77", sound: "elarbol", caption: "el árbol"},
		{id:"Prop78", sound: "elarbol", caption: "el árbol"},
		{id:"Prop79", sound: "lashojas", caption: "las hojas"},
		{id:"Prop80", sound: "lapalmera", caption: "la palmera"},
		{id:"Prop81", sound: "eltocon", caption: "el tocón"},
		{id:"Prop82", sound: "lasrocas", caption: "las rocas"},
		{id:"Prop83", sound: "larosa", caption: "las rosas"},
		{id:"Prop84", sound: "lasflores", caption: "las flores"},
		{id:"Prop85", sound: "elarbusto", caption: "el arbusto"},
		{id:"Prop86", sound: "elmanzano", caption: "el manzano"},
		{id:"Prop87", sound: "elarbolenmaceta", caption: "el árbol en maceta"},
		{id:"Prop88", sound: "lahierba", caption: "la hierba"},
		{id:"Prop89", sound: "lasparras", caption: "las parras"},
		{id:"Prop90", sound: "lacerca", caption: "la cerca"},
		{id:"Prop91", sound: "lacerca", caption: "la cerca"},
		{id:"Prop92", sound: "lospantalones", caption: "los pantalones"},
		{id:"Prop93", sound: "lospantelonescortos", caption: "los pantalones cortos"},
		{id:"Prop94", sound: "lasmedias", caption: "las medias"},
		{id:"Prop95", sound: "laropainterior", caption: "la ropa interior"},
		{id:"Prop96", sound: "lasbotas", caption: "las botas"}
	],

	characters: [
		[
			{id:"LionRoar", caption: "el león"},
			{id:"LionChew", caption: "el león"},
			{id:"LionClap", caption: "el león"},
			{id:"Bull", caption: "el toro"},
			{id:"Hippo", caption: "el hipopótamo"},
			{id:"Elephant", caption: "el elefante"}
		],[
			{id:"MonkeyChew", caption: "el mono"},
			{id:"MonkeyWave", caption: "el mono"},
			{id:"MonkeySway", caption: "el mono"},
			{id:"MonkeySwing", caption: "el mono"},
			{id:"Croc", caption: "el cocodrilo"},
			{id:"CrocBall", caption: "“Balls. The balls.”"}
		],[
			{id:"CatPounce", caption: "el gatito"},
			{id:"Dog", caption: "el perrito"},
			{id:"Cow", caption: "la vaca"},
			{id:"Duck", caption: "el pato"},
			{id:"Goat", caption: "la cabra"},
			{id:"Sheep", caption: "la oveja"}
		],[
			{id:"Whale", caption: "la ballena"},
			{id:"FishJump", caption: "el pez"},
			{id:"TwoBirds", caption: "los loros"},
			{id:"BirdFly", caption: "el pájaro"},
			{id:"Turtle", caption: "la tortuga"},
			{id:"Starfish", caption: "la estrella de mar"}
		],[
			{id:"NoahHuh", caption: "Huh?"},
			{id:"NoahQuestion", caption: "I don't understand."},
			{id:"NoahLaugh", caption: "Noah"},
			{id:"NoahBananas", caption: "“Hola, Abuela. Bananas! I…”"},
			{id:"NoahSorry", caption: "“Sorry!”"},
			{id:"NoahFly", caption: "Noah"}
		],[
			{id:"CocoBall", caption: "Coco"},
			{id:"CocoBalloon", caption: "“Noah, I want a red balloon.”"},
			{id:"CocoNono", caption: "“No, no Noah.”"},
			{id:"PeqJump", caption: "Pequeño"},
			{id:"PeqEat", caption: "Pequeño"}
		],[
			{id:"GrandmaMorning", caption: "“Good morning, Noah.”"},
			{id:"GrandmaMilk", caption: "“Milk. Moo! Moo!”"},
			{id:"OldManRow", caption: "Señor Rodriguez"},
			{id:"MrsMartinez", caption: "“Hi, Noah. How are you?”"},
			{id:"FarmerBanana", caption: "“My bananas!”"}
		],[
			{id:"Slide", caption: "la niña en el tobogán"},
			{id:"FireRing", caption: "el domador de leones"},
			{id:"CircusTrain", caption: "el tren del circo"}
		]
	],

	titles: [
		{id: "BellyLaughs", sound: "title_bellylaughs"},
		{id: "JungleJumble", sound: "title_junglejumble"},
		{id: "LookOutBelow", sound: "title_lookoutbelow"},
		{id: "OutToLunch", sound: "title_outtolunch"},
		{id: "SkyLimit", sound: "title_theskysthelimit"},
		{id: "SailAway", sound: "title_sailaway"},
		{id: "FunnyFarm", sound: "title_funnyfarm"},
		{id: "CircusSillies", sound: "title_circussillies"}
	],

	musics: [
		{id: "ChaChaCha", sound: "music_chachacha"},
		{id: "CoolCat", sound: "music_coolcat"},
		{id: "SpookySounds", sound: "music_spookysounds"},
		{id: "DangerAhead", sound: "music_dangerahead"},
		{id: "EasyPeasy", sound: "music_easypeasy"},
		{id: "FiestaFun", sound: "music_fiestafun"},
		{id: "BanjoBounce", sound: "music_bounce"},
		{id: "TrickyMouse", sound: "music_trickymouse"}
	]
};